default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: GithubExplorer_development
  username: postgres
  password: password
  host: db
  port: 5432

test:
  <<: *default
  database: GithubExplorer_test

production:
  <<: *default
  database: GithubExplorer_production
